### ISSUE TITLE
절대 경로로 지정된 이미지를 상대 경로로 바꿔주세요

### ISSUE THREAD

**Issue by legna** [braw0402/InternationalSOS-Superhero#2]
https://github.com/braw0402/InternationalSOS-Superhero/blob/cf90d6c6e0edc388715ddadb4ecc6067961f750f/0.html#L14

img 태그의 이미지 주소가 절대 경로(absolute path)로 되어 있어 다른 PC 및 서버에서 실행 시 제대로 불러오지 못합니다. 상대 경로(relative path)로 변경해주세요.

**Comment by braw0402** [comment]
수정 완료 하였습니다. 그대는 영웅이오.
