### ISSUE TITLE
파일 이름에 공백을 없애주세요

### ISSUE THREAD

**Issue by legna** [braw0402/InternationalSOS-Superhero#3]
파일 이름에 공백이 들어가면 안되는 것은 아니지만, 다양한 이유로 지양하고 있습니다.
예를 들어, 현재처럼 HTML 파일에 공백이 들어갈 경우 추후 서버에 올릴 시 About me가 http://www.example.com/About%20me 처럼 자동 치환되게 되는데 이 경우 보기에 좋지 않습니다.
그래서 about-me와 같은 kebab case나 about_me와 같은 snake case 등으로 파일명 규칙을 변경해주세요.

[링크](https://en.wikipedia.org/wiki/Letter_case#Special_case_styles) : kebab case와 snake case 참고자료

**Comment by braw0402** [comment]
네 알겠습니다 스승님. 수정완료.
